language: node_js
node_js:
  - "8"
cache: 
  yarn
before_script:
  - "yarn global add gatsby"
script:
  - "gatsby build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: public
  target_branch: master
  on:
    branch: source
notifications:
  email:
    recipients:
      - $NOTIF_EMAIL
    on_success: always
    on_failure: always
